### ISSUE TITLE
Syntax error: "(" unexpected (expecting ";;")

### ISSUE THREAD

**Issue by mrdwab** [adihrustic/Mullvad-WireGuard-script#2]
I wanted to try this out, but I'm getting the following on Ubuntu 18.04 when running `sudo make install`:

```
Installing...
/bin/sh: 12: /etc/bash_completion.d/mullvad-completion: Syntax error: "(" unexpected (expecting ";;")
Makefile:2: recipe for target 'install' failed
make: *** [install] Error 2
```

Any suggestions or any additional information?

**Comment by adihrustic** [comment]
Made an error in the Makefile, should be fixed now. Download the updated version of the file or just clone the whole repo again. :)

**Comment by mrdwab** [comment]
Seems like it's all working now. Thanks!
